[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  included_files = ["prisma/**"]
  timeout = 10

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Each job must be its own array item:
[[scheduled.functions]]
  name = "weekly_digest"
  schedule = "0 14 * * 4"   # Thursdays 14:00 UTC

[[scheduled.functions]]
  name = "series_generate"
  schedule = "0 11 * * 1"   # Mondays 11:00 UTC (~7am ET)
