[build]
  command = "pnpm build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  included_files = ["prisma/**"]
  timeout = 10

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[scheduled.functions]]
  name = "weekly_digest"
  schedule = "0 14 * * 4"
  name = "series_generate"
  schedule = "0 11 * * 1" # Mondays 11:00 UTC (~7am ET)