[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
  [plugins.inputs]
  extract = true

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Long-lived, immutable cache for hashed/static assets
[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/chunks/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# JSON data (kept short so updates propagate quickly)
[[headers]]
  for = "/*.json"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

# HTML / site pages — short caching so changes deploy quickly
[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "^/events/(list|map)(/.*)?$"
  to = "/events/"
  status = 301
  force = true

[[redirects]]
  from = "^/(event|events)/[^/]+/[0-9]{4}-[0-9]{2}-[0-9]{2}(/.*)?$"
  to = "/events/"
  status = 301
  force = true

# generic trailing-slash redirect (keep last)
[[redirects]]
  from = "/:splat"
  to = "/:splat/"
  status = 301
  force = false
  conditions = { Country = [] }