[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Caching headers
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Redirect non-file paths without trailing slash to trailing-slash version
# Evaluate after any specific redirects; Netlify processes redirects top-to-bottom.
[[redirects]]
  from = "^/events/(list|map)(/.*)?$"
  to = "/events/"
  status = 301
  force = true

[[redirects]]
  from = "^/(event|events)/[^/]+/[0-9]{4}-[0-9]{2}-[0-9]{2}(/.*)?$"
  to = "/events/"
  status = 301
  force = true

# generic trailing-slash redirect (keep last)
[[redirects]]
  from = "/:splat"
  to = "/:splat/"
  status = 301
  force = false
  conditions = { Country = [] }